version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always
    web:
    image: php:7.3-apache
    container-name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./Ejecicio1-WEB-LOGIN:/var/www/html
