version: '3'

services:
  db:
    image: mysql:latest
    container_name: docker-mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
            - ./localhost.sql:/docker-entrypoint-initdb.d  
            - persistent:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default  
    restart: always
           
  web:
    build: .
    container_name: docker-php
    ports:
      - "8001:80"
    networks:
      - default  
    volumes:
      - ./Ejecicio1-WEB-LOGIN/:/var/www/html
    depends_on:
      - db
     
volumes:
    persistent:  
