version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_USER: proyecto
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network
    
  web:
    build: .
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./Ejecicio1-WEB-LOGIN/:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network  
      
  networks:
        app-network:
            driver: bridge  
