version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    restart: always
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./Ejecicio1-WEB-LOGIN/:/var/www/html
    links:
      - mysql
      
