version: '3'
services:
  web:
    build: .
    container_name: docker-php
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.18.0.5    
    volumes:
      - ./docs/:/var/www/html

      
